spring:
  config:
    activate:
      on-profile: real
  datasource:
    url: "jdbc:mysql://13.125.39.166:3306/goya_db"
    username: "goya"
    password: "Goya1234!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  lifecycle:
    timeout-per-shutdown-phase: 10s
server:
  port: 8888
  address: 0.0.0.0
  shutdown: graceful
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL_SLOW: INFO
    org.hibernate.stat: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
