spring:
  config:
      activate:
        on-profile: dev
  datasource:
    url: jdbc:h2:./data/testdb
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
server:
  port: 8888
  address: 0.0.0.0